# Required substituion variables:
# - _GATEAU_API_DOMAIN


steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - docker build -t gcr.io/$PROJECT_ID/gateau-api:${TAG_NAME} -f Dockerfile .

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gateau-api:${TAG_NAME}"]

  # Deploy service image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - >
        gcloud
        run deploy ${TAG_NAME}-gateau-api
        --cpu 1
        --memory 256M
        --max-instances 5
        --image gcr.io/$PROJECT_ID/gateau-api:${TAG_NAME}
        --region europe-west1
        --platform managed
        --allow-unauthenticated

  # Apply domain mapping
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - >
        gcloud
        beta run domain-mappings create
        --service ${TAG_NAME}-gateau-api
        --domain ${TAG_NAME}.${_GATEAU_API_DOMAIN}
        --region europe-west1
        --force-override
