# Required substituion variables:
# - _GATEAU_API_DOMAIN

steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - docker build -t gcr.io/$PROJECT_ID/gateau-api:${TAG_NAME} -f Dockerfile .

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gateau-api:${TAG_NAME}"]

  # Update Firebase Database Rules
  - name: gcr.io/$PROJECT_ID/firebase
    args:
      - deploy
      - --project=gateau-api
      - --only=database
    secretEnv:
      - FIREBASE_TOKEN

  # Deploy service image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - >
        gcloud
        run deploy ${TAG_NAME}-gateau-api
        --cpu 1
        --memory 256M
        --max-instances 5
        --image gcr.io/$PROJECT_ID/gateau-api:${TAG_NAME}
        --region europe-west1
        --platform managed
        --allow-unauthenticated
        --set-env-vars FIREBASE_API_KEY=$$FIREBASE_API_KEY,FIREBASE_AUTH_DOMAIN=$$FIREBASE_AUTH_DOMAIN,FIREBASE_DATABASE_URL=$$FIREBASE_DATABASE_URL,FIREBASE_STORAGE_BUCKET=$$FIREBASE_STORAGE_BUCKET,FIREBASE_ADMIN_CREDENTIALS="$$FIREBASE_ADMIN_CREDENTIALS"
    secretEnv:
      - FIREBASE_API_KEY
      - FIREBASE_AUTH_DOMAIN
      - FIREBASE_DATABASE_URL
      - FIREBASE_STORAGE_BUCKET
      - FIREBASE_ADMIN_CREDENTIALS

  # Apply domain mapping. Cheap idempotency by ignoring failures.
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - >
        gcloud
        beta run domain-mappings create
        --service ${TAG_NAME}-gateau-api
        --domain ${TAG_NAME}.${_GATEAU_API_DOMAIN}
        --region europe-west1
        || true

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_API_KEY/versions/latest
      env: "FIREBASE_API_KEY"
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_AUTH_DOMAIN/versions/latest
      env: "FIREBASE_AUTH_DOMAIN"
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_DATABASE_URL/versions/latest
      env: "FIREBASE_DATABASE_URL"
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_STORAGE_BUCKET/versions/latest
      env: "FIREBASE_STORAGE_BUCKET"
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_ADMIN_CREDENTIALS/versions/latest
      env: "FIREBASE_ADMIN_CREDENTIALS"
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TOKEN/versions/latest
      env: "FIREBASE_TOKEN"
