import os

FIREBASE_DATABASE_URL = os.environ.get("FIREBASE_DATABASE_URL", "")

FIREBASE_API_KEY = os.environ.get("FIREBASE_API_KEY", "")

FIREBASE_AUTH_DOMAIN = os.environ.get("FIREBASE_AUTH_DOMAIN", "")

FIREBASE_STORAGE_BUCKET = os.environ.get("FIREBASE_STORAGE_BUCKET", "")

FIREBASE_ADMIN_CREDENTIALS = os.environ.get("FIREBASE_ADMIN_CREDENTIALS", "")

TESTING_PROJECT_ID = os.environ.get("TESTING_PROJECT_ID", "")
