"""
Routes that don't need an authed user to interact with
"""

import logging
from typing import Optional

from fastapi import APIRouter

logger = logging.getLogger(__name__)


router = APIRouter()


@router.get("/tokens/claim")
async def claim_token(
    corrId: Optional[str] = None,
):
    """
    Desktop client - claim a login token generated by the login screen
    """
    pass
