name: Update Major Version Tag

on:
  push:
    tags:
      - 'v*'
  create:
    tags:
      - 'v*'


jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
