name: Maintain major version and latest tags

on:
  push:
    tags:
      - v*

jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
